add_subdirectory(asrc)
add_subdirectory(bjt)
add_subdirectory(bsim1)
add_subdirectory(bsim2)
add_subdirectory(bsim3)
add_subdirectory(bsim3soi_dd)
add_subdirectory(bsim3soi_fd)
add_subdirectory(bsim3soi_pd)
add_subdirectory(bsim3v0)
add_subdirectory(bsim3v1)
add_subdirectory(bsim3v32)
add_subdirectory(bsim4)
add_subdirectory(bsim4v5)
add_subdirectory(bsim4v6)
add_subdirectory(bsim4v7)
add_subdirectory(bsimsoi)
add_subdirectory(cap)
add_subdirectory(cccs)
add_subdirectory(ccvs)
add_subdirectory(cpl)
add_subdirectory(csw)
add_subdirectory(dio)
add_subdirectory(hfet1)
add_subdirectory(hfet2)
add_subdirectory(hicum2)
add_subdirectory(hisim2)
add_subdirectory(hisimhv1)
add_subdirectory(hisimhv2)
add_subdirectory(ind)
add_subdirectory(isrc)
add_subdirectory(jfet)
add_subdirectory(jfet2)
add_subdirectory(ltra)
add_subdirectory(mes)
add_subdirectory(mesa)
add_subdirectory(mos1)
add_subdirectory(mos2)
add_subdirectory(mos3)
add_subdirectory(mos6)
add_subdirectory(mos9)
# add_subdirectory(nbjt)
# add_subdirectory(nbjt2)
add_subdirectory(ndev)
# add_subdirectory(numd)
# add_subdirectory(numd2)
# add_subdirectory(numos)
add_subdirectory(res)
add_subdirectory(soi3)
add_subdirectory(sw)
add_subdirectory(tra)
add_subdirectory(txl)
add_subdirectory(urc)
add_subdirectory(vbic)
add_subdirectory(vccs)
add_subdirectory(vcvs)
add_subdirectory(vdmos)
add_subdirectory(vsrc)

# Collect all source files in this subfolder
file(GLOB SOURCES "*.c")

# Create a library or executable (adjust as necessary)
add_library(devices_lib ${SOURCES})

